[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['rm -rf node_modules', 'npm install', 'npm run build', 'ls -la public/build']

[start]
cmd = 'sh Procfile'
